-- madang 계정 생성
DROP USER madang CASCADE; -- 확인 필요?
-- 계정명 : madang / 비밀번호 : madang
CREATE USER madang IDENTIFIED BY madang DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT; 
GRANT CONNECT, RESOURCE TO madang;
GRANT CREATE VIEW, CREATE SYNONYM TO madang;
GRANT UNLIMITED TABLESPACE TO madang;
ALTER USER madang ACCOUNT UNLOCK;

DROP USER scott CASCADE;
CREATE USER scott IDENTIFIED BY tiger DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO scott;
GRANT CREATE VIEW, CREATE SYNONYM TO scott;
GRANT UNLIMITED TABLESPACE TO scott;
ALTER USER scott ACCOUNT UNLOCK;